spring:
  redis:
    database: 0
    port: 6379
  cache:
    type: redis
    host: localhost
    port: 6379
  application:
    name: BinanceWS

springdoc:
  swagger-ui:
    path: /swagger-ui.html

binance:
  app:
    api-key: API_KEY
    secret-key: SECRET_KEY
    base-uri: wss://ws-api.binance.com:443/ws-api/v3
    base-uri-2: wss://stream.binance.com:9443/ws/{symbol}@ticker
